package com.zenyard.ghidra.illum;

import com.zenyard.ghidra.storage.InferenceStorage;

import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.LocalVariable;
import ghidra.program.model.listing.Variable;
import ghidra.program.model.pcode.Varnode;

/**
 * Utilities for name validation and variable lookup.
 */
public final class InferenceNameUtils {
    private InferenceNameUtils() {}

    public static boolean isValidName(String name) {
        if (name == null || name.isEmpty()) {
            return false;
        }
        if (!name.matches("^[a-zA-Z_][a-zA-Z0-9_]*$")) {
            return false;
        }
        return !name.startsWith("byte_")
            && !name.startsWith("word_")
            && !name.startsWith("dword_")
            && !name.startsWith("qword_");
    }

    public static boolean isPlaceholderName(String name) {
        if (name == null) {
            return true;
        }
        String normalized = name.toLowerCase();
        while (normalized.startsWith("_")) {
            normalized = normalized.substring(1);
        }
        return normalized.startsWith("undefined")
            || normalized.startsWith("unk_")
            || "unknown".equals(normalized);
    }

    /**
     * Normalize variable lookup names to improve matching between inference payloads and
     * decompiler-local names (e.g. strip array display suffixes like " [64]").
     */
    public static String normalizeVariableLookupName(String name) {
        if (name == null) {
            return null;
        }
        return name.replaceAll("\\s*\\[\\d+\\]\\s*$", "").trim();
    }

    /**
     * Heuristic for auto-generated decompiler variable names.
     */
    public static boolean isAutoGeneratedVariableName(String name) {
        if (name == null || name.isEmpty()) {
            return false;
        }
        String normalized = name;
        while (normalized.startsWith("_")) {
            normalized = normalized.substring(1);
        }
        String lower = normalized.toLowerCase();
        return lower.startsWith("local_")
            || lower.startsWith("uvar")
            || lower.startsWith("ivar")
            || lower.startsWith("fvar")
            || lower.startsWith("dvar")
            || lower.startsWith("bvar")
            || lower.startsWith("rvar")
            || lower.startsWith("prvar")
            || lower.startsWith("plvar")
            || lower.startsWith("puvar")
            || lower.startsWith("pcvar")
            || lower.startsWith("auvar")
            || lower.startsWith("unaff_")
            || lower.startsWith("extraout_")
            || lower.matches("^[a-z]{1,3}stack_[0-9a-f]+$")
            || lower.matches("^[a-z]+var\\d+$")
            || lower.matches("^[a-z]\\d+$");
    }

    /**
     * Extract numeric suffix from auto-generated variable names like puVar1/pRVar2/iVar3.
     */
    public static Integer extractAutoVarIndex(String name) {
        if (name == null) {
            return null;
        }
        String normalized = name;
        while (normalized.startsWith("_")) {
            normalized = normalized.substring(1);
        }
        String lower = normalized.toLowerCase();
        java.util.regex.Matcher matcher = java.util.regex.Pattern.compile("^[a-z]+var(\\d+)$").matcher(lower);
        if (matcher.matches()) {
            try {
                return Integer.parseInt(matcher.group(1));
            } catch (NumberFormatException e) {
                return null;
            }
        }

        matcher = java.util.regex.Pattern.compile("^[a-z]{1,3}stack_([0-9a-f]+)$").matcher(lower);
        if (matcher.matches()) {
            try {
                return Integer.parseInt(matcher.group(1), 16);
            } catch (NumberFormatException e) {
                return null;
            }
        }

        return null;
    }

    /**
     * Extract stack offset (as a negative value) from a stack variable name
     * like {@code acStack_58}, {@code auStack_58}, {@code local_58}.
     *
     * @return the negative stack offset, or {@code null} if the name is not a
     *         recognizable stack variable pattern.
     */
    public static Long extractStackOffset(String name) {
        if (name == null) {
            return null;
        }
        String lower = name.toLowerCase();
        java.util.regex.Matcher matcher = java.util.regex.Pattern.compile(
            "^[a-z]{1,3}stack_([0-9a-f]+)$"
        ).matcher(lower);
        if (matcher.matches()) {
            try {
                return -Long.parseLong(matcher.group(1), 16);
            } catch (NumberFormatException e) {
                return null;
            }
        }
        matcher = java.util.regex.Pattern.compile("^local_([0-9a-f]+)$").matcher(lower);
        if (matcher.matches()) {
            try {
                return -Long.parseLong(matcher.group(1), 16);
            } catch (NumberFormatException e) {
                return null;
            }
        }
        return null;
    }

    /**
     * Find a LocalVariable by stack offset. Searches all local variables in the
     * function for one whose first storage varnode matches the given stack offset.
     */
    public static LocalVariable findLocalVariableByStackOffset(Function function, long stackOffset) {
        if (function == null) {
            return null;
        }
        for (Variable var : function.getLocalVariables()) {
            if (!(var instanceof LocalVariable)) {
                continue;
            }
            LocalVariable local = (LocalVariable) var;
            ghidra.program.model.listing.VariableStorage variableStorage = local.getVariableStorage();
            if (variableStorage == null) {
                continue;
            }
            Varnode[] varnodes = variableStorage.getVarnodes();
            if (varnodes == null || varnodes.length == 0) {
                continue;
            }
            for (Varnode vn : varnodes) {
                if (vn != null && vn.getAddress() != null && vn.getAddress().isStackAddress()) {
                    if (vn.getAddress().getOffset() == stackOffset) {
                        return local;
                    }
                }
            }
        }
        return null;
    }

    public static InferenceStorage.VariableStorageIdentity toStorageIdentity(Varnode storage) {
        if (storage == null || storage.getAddress() == null) {
            return null;
        }
        String kind;
        if (storage.getAddress().isUniqueAddress()) {
            kind = "unique";
        } else if (storage.getAddress().isStackAddress()) {
            kind = "stack";
        } else if (storage.getAddress().isRegisterAddress()) {
            kind = "register";
        } else {
            kind = "other";
        }
        return new InferenceStorage.VariableStorageIdentity(
            kind,
            storage.getAddress().toString(),
            storage.getSize()
        );
    }

    public static LocalVariable findLocalVariableByStorage(Function function, Varnode storage) {
        if (function == null || storage == null) {
            return null;
        }
        for (Variable var : function.getLocalVariables()) {
            if (var instanceof LocalVariable) {
                LocalVariable local = (LocalVariable) var;
                ghidra.program.model.listing.VariableStorage variableStorage = local.getVariableStorage();
                if (variableStorage == null) {
                    continue;
                }
                ghidra.program.model.pcode.Varnode[] varnodes = variableStorage.getVarnodes();
                if (varnodes != null) {
                    for (ghidra.program.model.pcode.Varnode varnode : varnodes) {
                        if (storage.equals(varnode)) {
                            return local;
                        }
                        if (varnode != null && storage.getAddress().equals(varnode.getAddress())) {
                            return local;
                        }
                    }
                }
            }
        }
        return null;
    }
}
