package com.zenyard.ghidra.illum;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class InferenceNameUtilsTest {

    @Test
    void normalizesArraySuffixForLookup() {
        assertEquals("acStack_58", InferenceNameUtils.normalizeVariableLookupName("acStack_58 [64]"));
        assertEquals("local_message", InferenceNameUtils.normalizeVariableLookupName("local_message[64]"));
        assertEquals("plainName", InferenceNameUtils.normalizeVariableLookupName("plainName"));
    }

    @Test
    void recognizesAcStackAsAutoGeneratedVariableName() {
        assertTrue(InferenceNameUtils.isAutoGeneratedVariableName("acStack_58"));
        assertTrue(InferenceNameUtils.isAutoGeneratedVariableName("auStack_58"));
        assertTrue(InferenceNameUtils.isAutoGeneratedVariableName("auStack_a8"));
        assertTrue(InferenceNameUtils.isAutoGeneratedVariableName("_acStack_120"));
    }

    @Test
    void extractsAutoVariableIndicesForKnownPatterns() {
        assertEquals(7, InferenceNameUtils.extractAutoVarIndex("puVar7"));
        assertEquals(0x58, InferenceNameUtils.extractAutoVarIndex("acStack_58"));
        assertEquals(0x58, InferenceNameUtils.extractAutoVarIndex("auStack_58"));
        assertEquals(0xa8, InferenceNameUtils.extractAutoVarIndex("auStack_a8"));
        assertNull(InferenceNameUtils.extractAutoVarIndex("local_message"));
    }
}
